#!/usr/bin/env bash
# Assemble the release bundle directory for one commit (ARCHITECTURE.md,
# "Server deployment", "Artifacts" and "The manifest"). Every file is taken
# from the commit itself with `git show`, not from the working tree, so the
# bundle is exactly what was tested. The image references come from the
# environment and must already be digests; the manifest is written with jq
# and validated before the script succeeds.
#
#   RELEASE_COMMIT=<40 hex> RELEASE_RUN_ID=<n> RELEASE_RUN_ATTEMPT=<n> \
#   IMAGE_ORCHESTRATOR=… IMAGE_NGINX=… IMAGE_SESSION_CLAUDE=… IMAGE_SESSION_CLAUDE_DEV=… \
#     scripts/release/make-bundle.sh <output-dir>
#
# <output-dir> must not exist; the bundle is written to <output-dir>/bundle.
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <output-dir>" >&2
  exit 2
fi
out=$1
if [ -e "$out" ]; then
  echo "${out} already exists" >&2
  exit 2
fi
for var in RELEASE_COMMIT RELEASE_RUN_ID RELEASE_RUN_ATTEMPT \
  IMAGE_ORCHESTRATOR IMAGE_NGINX IMAGE_SESSION_CLAUDE IMAGE_SESSION_CLAUDE_DEV; do
  if [ -z "${!var:-}" ]; then
    echo "${var} is required" >&2
    exit 2
  fi
done
commit=$RELEASE_COMMIT
here=$(cd "$(dirname "$0")" && pwd)

show() { git show "${commit}:$1"; }

bundle="${out}/bundle"
mkdir -p "${bundle}/scripts" "${bundle}/bin"

show compose.yml >"${bundle}/compose.yml"
show compose.podman.yml >"${bundle}/compose.podman.yml"
show scripts/verify-deployment.sh >"${bundle}/scripts/verify-deployment.sh"
mkdir -p "${bundle}/lib"
show deploy/lib/envfile.sh >"${bundle}/lib/envfile.sh"
show deploy/bin/check-env >"${bundle}/bin/check-env"
show deploy/bin/session-images >"${bundle}/bin/session-images"
show deploy/bin/mars-backup >"${bundle}/bin/mars-backup"
show .env.example >"${bundle}/env.example"
chmod 0755 "${bundle}/scripts/verify-deployment.sh" "${bundle}/bin/check-env" "${bundle}/bin/session-images" "${bundle}/bin/mars-backup"

# The two services the release replaces, pinned to this release's digests.
# compose.yml's `build:` sections stay: `build: !reset null` would drop them,
# but podman-compose 1.6.0 crashes on `!reset` under `build` (it only
# tolerates it where compose.hostrun.yml uses it, on `depends_on`). They are
# harmless here: the updater pulls every image by digest before `up`, compose
# starts a present image without building, and the bundle carries no build
# context, so a missing image fails with "Dockerfile not found" instead of
# ever building on the server.
cat >"${bundle}/compose.release.yml" <<YAML
# Generated by scripts/release/make-bundle.sh for ${commit}.
# ARCHITECTURE.md, "Server deployment": images by digest, pulled before
# \`up\` and never built on the server.
services:
  orchestrator:
    image: ${IMAGE_ORCHESTRATOR}
  nginx:
    image: ${IMAGE_NGINX}
YAML

epoch=$(show deploy/EPOCH | tr -d '[:space:]')
epoch_note=$(show deploy/EPOCH_NOTE 2>/dev/null || true)
sequence=$(git rev-list --count "$commit")

migrations=$(git ls-tree --name-only "${commit}:orchestrator/migrations" |
  sed -n 's/^\([0-9]\{14\}\)_.*\.up\.sql$/\1/p' | sort | jq -R . | jq -s .)
required=$(show deploy/required-config | sed -e 's/#.*//' -e 's/[[:space:]]//g' | grep -v '^$' |
  jq -R . | jq -s .)
# The PostgreSQL major compose.yml defaults to, `${POSTGRES_IMAGE:-postgres:<major>}`.
# shellcheck disable=SC2016 # the ${…} is compose syntax matched literally, not shell
postgres_major=$(show compose.yml |
  sed -n 's/^[[:space:]]*image:[[:space:]]*\${POSTGRES_IMAGE:-postgres:\([0-9][0-9]*\)[^}]*}.*$/\1/p' | head -1)
if [ -z "$postgres_major" ]; then
  # shellcheck disable=SC2016 # printed literally: it names compose syntax
  echo 'compose.yml names no ${POSTGRES_IMAGE:-postgres:<major>} image' >&2
  exit 1
fi

jq -n \
  --argjson epoch "$epoch" \
  --arg epoch_note "$epoch_note" \
  --arg commit "$commit" \
  --argjson sequence "$sequence" \
  --argjson run_id "$RELEASE_RUN_ID" \
  --argjson run_attempt "$RELEASE_RUN_ATTEMPT" \
  --arg published_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --arg orchestrator "$IMAGE_ORCHESTRATOR" \
  --arg nginx "$IMAGE_NGINX" \
  --arg session_claude "$IMAGE_SESSION_CLAUDE" \
  --arg session_claude_dev "$IMAGE_SESSION_CLAUDE_DEV" \
  --argjson migrations "$migrations" \
  --argjson required "$required" \
  --argjson postgres_major "$postgres_major" \
  '{
    format: 1,
    epoch: $epoch,
    epoch_note: $epoch_note,
    source: {
      repository: "LHelge/mars",
      commit: $commit,
      sequence: $sequence,
      run_id: $run_id,
      run_attempt: $run_attempt,
      published_at: $published_at
    },
    platform: "linux/amd64",
    images: {
      orchestrator: $orchestrator,
      nginx: $nginx,
      session_claude: $session_claude,
      session_claude_dev: $session_claude_dev
    },
    schema: { migrations: $migrations },
    config: { required: $required },
    postgres: { major: $postgres_major }
  }' >"${bundle}/manifest.json"

"${here}/validate-manifest.sh" "${bundle}/manifest.json"

# The image the bundle is published as: files only, never run.
cat >"${out}/Containerfile" <<'CF'
FROM scratch
COPY bundle /bundle
CF
