//! `POST /api/auth/request-password-reset` and `POST /api/auth/reset-password`
//! through the real router (`SPEC.md`, "Auth (`/api/auth`)";
//! "Authentication").
//!
//! The request half has one response and several behaviours behind it: 204 for
//! a known identifier, an unknown one, a rate-limited one and a failed
//! delivery alike, so everything these tests assert about *which* of those
//! happened is asserted through the mock email client rather than through the
//! response (`CLAUDE.md`, "Testing expectations": invite and reset flows are
//! asserted through the captured messages).
//!
//! The consume half is the single-use rule of `docs/data-model.md`,
//! `password_reset_tokens`: a link may be spent once, is invalidated by any
//! other password change, expires after an hour, and never logs anybody in.
//!
//! Every password and token in this file is obviously fake, or generated by
//! the orchestrator under test (`CLAUDE.md`, rule 3).
//!
//! Needs a container engine (`DOCKER_HOST`); see `tests/common/db.rs`.

#![cfg(feature = "integration-tests")]

mod common;

use axum::http::StatusCode;
use axum::http::header::SET_COOKIE;
use chrono::{DateTime, Utc};
use common::TestApp;
use mars_orchestrator::auth::REFRESH_COOKIE;
use mars_orchestrator::models::OpaqueToken;
use mars_orchestrator::prelude::*;
use serde_json::{Value, json};
use uuid::Uuid;

const REQUEST: &str = "/api/auth/request-password-reset";
const RESET: &str = "/api/auth/reset-password";
const ME: &str = "/api/users/me";

/// Obviously fake, and long enough for the documented 10–128 range.
const PASSWORD: &str = "correct-horse-battery-staple";

/// The replacement, equally fake and equally long enough.
const NEW_PASSWORD: &str = "a-completely-different-phrase";

/// The prefix of the emailed link, from the harness `PUBLIC_URL`.
const LINK_PREFIX: &str = "http://localhost/reset-password/";

/// The documented 400 body for a token this endpoint will not accept.
fn invalid_token() -> Value {
    json!({ "status": 400, "error": "invalid or expired token" })
}

/// How many reset tokens the database holds.
///
/// A row-level fact: the endpoint answers 204 whether or not it wrote one, so
/// nothing but the row says whether a link was issued.
async fn reset_token_rows(app: &TestApp) -> i64 {
    sqlx::query_scalar("SELECT COUNT(*) FROM password_reset_tokens")
        .fetch_one(&app.pool)
        .await
        .expect("the count succeeds")
}

#[tokio::test]
async fn a_request_for_a_known_email_sends_exactly_one_link() {
    let app = TestApp::spawn().await;
    let user = app
        .insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    app.request_reset_link("ada@example.test").await;

    let sent = app.mock_email().sent();
    assert_eq!(sent.len(), 1);
    assert_eq!(sent[0].to, "ada@example.test");
    assert!(sent[0].text.contains(LINK_PREFIX), "{}", sent[0].text);

    // The row carries the hash of the emailed token and nothing that resembles
    // the token itself (`docs/data-model.md`).
    let token = app.reset_link_token(0);
    let row: (Uuid, String, Option<DateTime<Utc>>, DateTime<Utc>) = sqlx::query_as(
        "SELECT user_id, token_hash, used_at, expires_at FROM password_reset_tokens",
    )
    .fetch_one(&app.pool)
    .await
    .expect("exactly one reset token row");
    assert_eq!(row.0, user.id);
    assert_eq!(row.1, OpaqueToken::hash_of(&token));
    assert_ne!(row.1, token, "the raw token must never be stored");
    assert_eq!(row.2, None);

    // One hour, the documented reset-link validity (`SPEC.md`, "User-facing
    // features").
    let ttl = row.3 - Utc::now();
    assert!(
        ttl > PASSWORD_RESET_TTL - chrono::TimeDelta::minutes(1) && ttl <= PASSWORD_RESET_TTL,
        "unexpected expiry: {ttl}"
    );
}

/// The identifier is "your username or email", so a username works too, and
/// the email is matched after trimming and lower-casing (`SPEC.md`,
/// "Authentication").
#[tokio::test]
async fn a_request_by_username_or_by_a_differently_cased_email_finds_the_same_user() {
    let app = TestApp::spawn().await;
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    app.request_reset_link("ada").await;
    app.request_reset_link("  ADA@Example.TEST  ").await;

    let sent = app.mock_email().sent();
    assert_eq!(sent.len(), 2);
    assert!(sent.iter().all(|message| message.to == "ada@example.test"));
}

#[tokio::test]
async fn a_request_for_an_unknown_identifier_is_204_and_sends_nothing() {
    let app = TestApp::spawn().await;
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    app.request_reset_link("nobody").await;
    app.request_reset_link("nobody@example.test").await;

    assert!(app.mock_email().sent().is_empty());
    assert_eq!(reset_token_rows(&app).await, 0);
}

/// Three per identifier per hour, and the fourth is still a 204 (`SPEC.md`,
/// "User-facing features").
#[tokio::test]
async fn the_fourth_request_within_the_hour_sends_nothing_and_still_answers_204() {
    let app = TestApp::spawn().await;
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    for _ in 0..4 {
        app.request_reset_link("ada@example.test").await;
    }

    assert_eq!(app.mock_email().sent().len(), 3);
    assert_eq!(reset_token_rows(&app).await, 3);

    // The limit is a fact about the limiter, not about the account.
    app.reset_limiters();
    app.request_reset_link("ada@example.test").await;
    assert_eq!(app.mock_email().sent().len(), 4);
}

/// An unknown identifier counts against the limit too, which is what keeps the
/// limited and unlimited paths from differing in observable work.
#[tokio::test]
async fn an_unknown_identifier_is_counted_by_the_limiter() {
    let app = TestApp::spawn().await;

    for _ in 0..3 {
        app.request_reset_link("ada@example.test").await;
    }

    // Only now is the user created; the limit was already spent by the
    // requests that found nobody.
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;
    app.request_reset_link("ada@example.test").await;

    assert!(app.mock_email().sent().is_empty());
}

/// A provider failure is the operator's problem: the token is committed and
/// the caller still gets 204 (ADR 0014, ADR 0026).
#[tokio::test]
async fn a_failed_delivery_still_answers_204() {
    let app = TestApp::spawn().await;
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;
    app.mock_email().fail_next();

    app.request_reset_link("ada@example.test").await;

    assert!(app.mock_email().sent().is_empty());
    assert_eq!(reset_token_rows(&app).await, 1);
}

#[tokio::test]
async fn a_reset_sets_the_password_revokes_the_logins_and_does_not_sign_anybody_in() {
    let app = TestApp::spawn().await;
    let user = app
        .insert_user_with_password("ada", "ada@example.test", PASSWORD, false, true)
        .await;
    let (pair, cookie) = app.login("ada", PASSWORD).await;

    app.request_reset_link("ada@example.test").await;
    let token = app.reset_link_token(0);

    let response = app.reset_password(&token, NEW_PASSWORD).await;

    response.assert_status(StatusCode::NO_CONTENT);
    assert!(response.text().is_empty());
    assert_eq!(response.headers().get(SET_COOKIE), None);

    // The whole credential moved, which the old half of it proves: the cookie
    // and the access token minted before the reset are both refused, so every
    // refresh token was revoked and `auth_version` moved on.
    app.refresh(&cookie)
        .await
        .assert_status(StatusCode::UNAUTHORIZED);
    app.server
        .get(ME)
        .authorization_bearer(&pair.access_token)
        .await
        .assert_status(StatusCode::UNAUTHORIZED);

    // The password itself changed, and the gate the user was under is cleared
    // — both of them as the login that follows the reset sees them.
    app.server
        .post("/api/auth/login")
        .json(&json!({ "username": "ada", "password": PASSWORD }))
        .await
        .assert_status(StatusCode::UNAUTHORIZED);
    let (after, _cookie) = app.login("ada", NEW_PASSWORD).await;
    assert_eq!(after.user["id"], json!(user.id.to_string()));
    assert_eq!(after.user["must_change_password"], json!(false));
}

#[tokio::test]
async fn a_link_cannot_be_used_twice() {
    let app = TestApp::spawn().await;
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    app.request_reset_link("ada@example.test").await;
    let token = app.reset_link_token(0);

    app.reset_password(&token, NEW_PASSWORD)
        .await
        .assert_status(StatusCode::NO_CONTENT);

    let response = app.reset_password(&token, "yet-another-phrase").await;

    response.assert_status(StatusCode::BAD_REQUEST);
    assert_eq!(response.json::<Value>(), invalid_token());
    // And the second attempt changed nothing: the first password still logs in.
    app.login("ada", NEW_PASSWORD).await;
}

/// Single use is per user: spending one link invalidates the other outstanding
/// ones (`docs/data-model.md`, `password_reset_tokens`).
#[tokio::test]
async fn spending_one_link_invalidates_the_others() {
    let app = TestApp::spawn().await;
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    app.request_reset_link("ada@example.test").await;
    app.request_reset_link("ada@example.test").await;
    let first = app.reset_link_token(0);
    let second = app.reset_link_token(1);
    assert_ne!(first, second);

    app.reset_password(&second, NEW_PASSWORD)
        .await
        .assert_status(StatusCode::NO_CONTENT);

    let response = app.reset_password(&first, "yet-another-phrase").await;
    response.assert_status(StatusCode::BAD_REQUEST);
    assert_eq!(response.json::<Value>(), invalid_token());
}

/// Any password change invalidates outstanding links, not just another reset
/// (`SPEC.md`, "Authentication").
#[tokio::test]
async fn a_self_service_change_invalidates_an_outstanding_link() {
    let app = TestApp::spawn().await;
    let user = app
        .insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    app.request_reset_link("ada@example.test").await;
    let token = app.reset_link_token(0);

    let (pair, _cookie) = app.login("ada", PASSWORD).await;
    app.server
        .post(&format!("/api/users/{}/password", user.id))
        .authorization_bearer(&pair.access_token)
        .json(&json!({ "current_password": PASSWORD, "password": NEW_PASSWORD }))
        .await
        .assert_status(StatusCode::OK);

    let response = app.reset_password(&token, "yet-another-phrase").await;

    response.assert_status(StatusCode::BAD_REQUEST);
    assert_eq!(response.json::<Value>(), invalid_token());
    app.login("ada", NEW_PASSWORD).await;
}

#[tokio::test]
async fn an_expired_link_is_400() {
    let app = TestApp::spawn().await;
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    app.request_reset_link("ada@example.test").await;
    let token = app.reset_link_token(0);

    // A row-level fact with no interface: the expiry lives in the row and no
    // route moves it, so it is aged past its hour the way the clock would have
    // done on its own.
    sqlx::query("UPDATE password_reset_tokens SET expires_at = NOW() - INTERVAL '1 minute'")
        .execute(&app.pool)
        .await
        .expect("the token ages");

    let response = app.reset_password(&token, NEW_PASSWORD).await;

    response.assert_status(StatusCode::BAD_REQUEST);
    assert_eq!(response.json::<Value>(), invalid_token());
    app.login("ada", PASSWORD).await;
}

/// An unknown token is the same 400 as a spent or expired one: the endpoint
/// never says which.
#[tokio::test]
async fn an_unknown_token_is_the_same_400() {
    let app = TestApp::spawn().await;

    let response = app
        .reset_password("not-a-real-reset-token", NEW_PASSWORD)
        .await;

    response.assert_status(StatusCode::BAD_REQUEST);
    assert_eq!(response.json::<Value>(), invalid_token());
    assert_eq!(response.maybe_cookie(REFRESH_COOKIE), None);
}

/// The 10–128 rule applies to a reset as much as to a change, and the token is
/// not spent by a rejected attempt.
#[tokio::test]
async fn a_password_outside_the_documented_range_is_400_and_keeps_the_link() {
    let app = TestApp::spawn().await;
    app.insert_user_with_password("ada", "ada@example.test", PASSWORD, false, false)
        .await;

    app.request_reset_link("ada@example.test").await;
    let token = app.reset_link_token(0);

    let response = app.reset_password(&token, "too-short").await;

    response.assert_status(StatusCode::BAD_REQUEST);
    assert_eq!(
        response.json::<Value>(),
        json!({ "status": 400, "error": "password must be 10-128 characters" })
    );

    // Still usable: nothing was written.
    app.reset_password(&token, NEW_PASSWORD)
        .await
        .assert_status(StatusCode::NO_CONTENT);
}

#[tokio::test]
async fn a_body_missing_a_field_is_400() {
    let app = TestApp::spawn().await;

    for (route, body) in [
        (REQUEST, json!({})),
        (RESET, json!({ "token": "not-a-real-reset-token" })),
        (RESET, json!({ "password": NEW_PASSWORD })),
    ] {
        let response = app.server.post(route).json(&body).await;

        response.assert_status(StatusCode::BAD_REQUEST);
        assert_eq!(response.json::<Value>()["status"], json!(400), "{body}");
    }
}
