//! `auth::Credentials` driven directly, without a route in the way
//! (`ARCHITECTURE.md`, "User authentication and revocation"; `SPEC.md`,
//! "Authentication"; ADR 0025).
//!
//! The `auth_*` and `users_password` suites assert what the seven handlers
//! answer over HTTP. This one asserts the thing underneath them: that the
//! module is the only issuer, and that every promise about *how* a credential
//! comes into being holds whoever calls it. So the documented cookie
//! attributes are asserted once, here, rather than three times in three route
//! tests, and the rotation, the revocation and the ordering rules are asserted
//! against the module's own return values rather than against a `Set-Cookie`
//! header.
//!
//! Every password and token in this file is obviously fake, or generated by
//! the orchestrator under test (`CLAUDE.md`, rule 3).
//!
//! Needs a container engine (`DOCKER_HOST`); see `tests/common/db.rs`.

#![cfg(feature = "integration-tests")]

mod common;

use std::net::{IpAddr, Ipv4Addr};

use axum::http::StatusCode;
use axum_extra::extract::CookieJar;
use axum_extra::extract::cookie::{Cookie, SameSite};
use chrono::Utc;
use common::TestApp;
use common::races::{IN_FLIGHT, RACE_TIMEOUT, hold_user_lock, unrevoked_refresh_tokens};
use mars_orchestrator::auth::{Credentials, IssuedPair, REFRESH_COOKIE};
use mars_orchestrator::models::user::hash_password;
use mars_orchestrator::models::{OpaqueToken, User};
use mars_orchestrator::prelude::*;
use mars_orchestrator::repositories::{
    PasswordResetTokenRepository, UserRepository, password_reset_tokens,
};
use tokio::time::{sleep, timeout};
use uuid::Uuid;

/// Obviously fake, and long enough for the documented 10–128 range.
const PASSWORD: &str = "correct-horse-battery-staple";

/// The replacement, equally fake and equally long enough.
const NEW_PASSWORD: &str = "a-completely-different-phrase";

const USERNAME: &str = "ada";
const EMAIL: &str = "ada@example.test";

/// The client address the throttle keys on; the loopback, as an unproxied
/// request would give.
fn client() -> IpAddr {
    IpAddr::V4(Ipv4Addr::LOCALHOST)
}

/// A user whose password actually verifies.
async fn user(app: &TestApp) -> User {
    app.insert_user_with_password(USERNAME, EMAIL, PASSWORD, false, false)
        .await
}

/// The jar a browser would send back after being given `cookie`.
///
/// Only the name and the value survive a round trip — `HttpOnly`, `Path` and
/// the rest are instructions to the browser, not things it echoes — so this is
/// what the module actually receives on the next request.
fn presented(cookie: &Cookie<'static>) -> CookieJar {
    CookieJar::new().add(Cookie::new(REFRESH_COOKIE, cookie.value().to_string()))
}

/// The user row as it now stands.
async fn stored(app: &TestApp, id: Uuid) -> User {
    UserRepository::new(&app.pool)
        .find(id)
        .await
        .expect("the lookup runs")
        .expect("the user is there")
}

/// A pair is issued, its access token verifies against the committed row, and
/// its cookie carries exactly the attributes `SPEC.md`, "Authentication"
/// fixes.
///
/// The one place those attributes are asserted: they are written once, in
/// `auth::cookies`, so asserting them once is the matching arrangement.
#[tokio::test]
async fn login_issues_a_pair_with_the_documented_cookie() {
    let app = TestApp::spawn().await;
    let ada = user(&app).await;

    let IssuedPair {
        user,
        access_token,
        refresh_cookie,
    } = Credentials::new(&app.state)
        .login(USERNAME, PASSWORD, client())
        .await
        .expect("the credentials are accepted");

    assert_eq!(user.id, ada.id);

    // Minted from the committed row, so the claims are the row's.
    let claims = Claims::decode(&access_token, &app.state.config).expect("the token verifies");
    assert_eq!(claims.sub, ada.id);
    assert_eq!(claims.auth_version, ada.auth_version);

    assert_eq!(refresh_cookie.name(), REFRESH_COOKIE);
    assert_eq!(refresh_cookie.http_only(), Some(true));
    assert_eq!(refresh_cookie.same_site(), Some(SameSite::Lax));
    assert_eq!(refresh_cookie.path(), Some("/"));
    assert_eq!(
        refresh_cookie.max_age().expect("a max-age").whole_seconds(),
        REFRESH_TOKEN_TTL.num_seconds()
    );
    // The harness `PUBLIC_URL` is plain http, so `Secure` is off; over https it
    // is on, which `auth::cookies` asserts in its own unit tests.
    assert_eq!(refresh_cookie.secure(), Some(false));

    // The raw token is the cookie's value and nothing else; the row holds only
    // its hash, and it is committed and usable.
    assert_ne!(refresh_cookie.value(), "");
    assert_eq!(unrevoked_refresh_tokens(&app.pool, ada.id).await, 1);
}

/// A wrong password is refused with the same message an unknown username gets,
/// and the failure is counted against the throttle.
#[tokio::test]
async fn a_wrong_password_and_an_unknown_username_are_the_same_rejection() {
    let app = TestApp::spawn().await;
    user(&app).await;
    let credentials = Credentials::new(&app.state);

    for (username, password) in [(USERNAME, "not-the-password"), ("nobody", PASSWORD)] {
        let err = credentials
            .login(username, password, client())
            .await
            .expect_err("the credentials are refused");

        assert_eq!(err.status(), StatusCode::UNAUTHORIZED);
        assert_eq!(err.user_message(), "invalid username or password");
    }

    // Two failures were recorded, one per key pair, and neither issued
    // anything.
    assert!(app.state.login_throttle.tracked_keys() > 0);
}

/// Refreshing rotates: the presented token is revoked in the same transaction
/// that inserts its replacement, and presenting it again fails.
#[tokio::test]
async fn refresh_rotates_and_revokes_the_presented_token() {
    let app = TestApp::spawn().await;
    let ada = user(&app).await;
    let credentials = Credentials::new(&app.state);

    let first = credentials
        .login(USERNAME, PASSWORD, client())
        .await
        .expect("the login succeeds");
    let presented_first = presented(&first.refresh_cookie);

    let second = credentials
        .refresh(&presented_first)
        .await
        .expect("the rotation succeeds");

    assert_eq!(second.user.id, ada.id);
    assert_ne!(
        second.refresh_cookie.value(),
        first.refresh_cookie.value(),
        "the refresh token must be rotated"
    );

    // One in, one out: the replacement is the only usable token.
    assert_eq!(unrevoked_refresh_tokens(&app.pool, ada.id).await, 1);

    // The presented token is spent, and the same 401 a missing cookie gets.
    let err = credentials
        .refresh(&presented_first)
        .await
        .expect_err("a revoked token is refused");
    assert_eq!(err.status(), StatusCode::UNAUTHORIZED);
    assert_eq!(err.user_message(), "authentication required");

    // The replacement still works.
    credentials
        .refresh(&presented(&second.refresh_cookie))
        .await
        .expect("the replacement rotates in turn");
}

/// A refresh that reaches its lock after a password change committed loses:
/// the authoritative read under the lock finds the token revoked.
///
/// The deterministic form of the race `tests/auth_revocation_race.rs` runs
/// over HTTP — the user row is held while the refresh is in flight, so the
/// refresh provably reaches `lock_user` after the change committed (ADR 0025).
#[tokio::test]
async fn a_refresh_racing_a_password_change_loses() {
    let app = TestApp::spawn().await;
    let ada = user(&app).await;
    let credentials = Credentials::new(&app.state);

    let issued = credentials
        .login(USERNAME, PASSWORD, client())
        .await
        .expect("the login succeeds");
    let jar = presented(&issued.refresh_cookie);

    // Taken before the refresh starts, so it blocks in `lock_user` — after it
    // has located the token row unlocked, and before it reads `revoked_at` for
    // the decision.
    let mut holder = hold_user_lock(&app.pool, ada.id).await;

    let refreshing = credentials.refresh(&jar);
    let changing = async {
        sleep(IN_FLIGHT).await;
        let hash = hash_password(NEW_PASSWORD).expect("the new password hashes");
        UserRepository::new(&app.pool)
            .apply_password_change(&mut holder, ada.id, &hash, None)
            .await
            .expect("the password change applies");
        holder.commit().await.expect("the holder commits");
    };

    let (refreshed, ()) = timeout(RACE_TIMEOUT, async { tokio::join!(refreshing, changing) })
        .await
        .expect("the refresh and the password change did not deadlock");

    let err = refreshed.expect_err("the refresh loses the race");
    assert_eq!(err.status(), StatusCode::UNAUTHORIZED);

    // Nothing was rotated into existence on the way out: the change issued no
    // replacement, so the user holds no usable token at all.
    assert_eq!(unrevoked_refresh_tokens(&app.pool, ada.id).await, 0);
    assert_eq!(stored(&app, ada.id).await.auth_version, 1);
}

/// Spending a reset link marks the token used and revokes every refresh token
/// the user had, and logs nobody in.
#[tokio::test]
async fn a_reset_spends_the_token_and_revokes_every_refresh_token() {
    let app = TestApp::spawn().await;
    let ada = user(&app).await;
    let credentials = Credentials::new(&app.state);

    // Two browsers signed in, so "every" is more than one.
    credentials
        .login(USERNAME, PASSWORD, client())
        .await
        .expect("the first login succeeds");
    credentials
        .login(USERNAME, PASSWORD, client())
        .await
        .expect("the second login succeeds");
    assert_eq!(unrevoked_refresh_tokens(&app.pool, ada.id).await, 2);

    let token = OpaqueToken::generate();
    let tokens = PasswordResetTokenRepository::new(&app.pool);
    let mut tx = app.pool.begin().await.expect("a transaction begins");
    tokens
        .insert(
            &mut tx,
            ada.id,
            &token.hash,
            password_reset_tokens::expires_at(Utc::now()),
        )
        .await
        .expect("the reset token inserts");
    tx.commit().await.expect("the transaction commits");

    credentials
        .reset_password(&token.raw, NEW_PASSWORD)
        .await
        .expect("the reset succeeds");

    // Nobody is signed in by a reset, and no earlier login survived it.
    assert_eq!(unrevoked_refresh_tokens(&app.pool, ada.id).await, 0);
    assert_eq!(stored(&app, ada.id).await.auth_version, 1);

    // The link is single-use, and a replay is the documented 400.
    let err = credentials
        .reset_password(&token.raw, NEW_PASSWORD)
        .await
        .expect_err("a spent link is refused");
    assert_eq!(err.status(), StatusCode::BAD_REQUEST);
    assert_eq!(err.user_message(), "invalid or expired token");

    // And the new password is the one that works.
    credentials
        .login(USERNAME, NEW_PASSWORD, client())
        .await
        .expect("the new password authenticates");
}

/// `change_password` returns a pair exactly when the caller asked to keep this
/// browser signed in, and the replacement is the only token left either way.
#[tokio::test]
async fn a_password_change_issues_a_replacement_only_when_it_is_asked_to() {
    let app = TestApp::spawn().await;
    let ada = user(&app).await;
    let credentials = Credentials::new(&app.state);

    credentials
        .login(USERNAME, PASSWORD, client())
        .await
        .expect("the login succeeds");

    // Self-service: one pair back, and exactly one usable token — the
    // replacement `apply_password_change` inserted after its own revocation.
    let issued = credentials
        .change_password(ada.id, Some(PASSWORD.to_string()), NEW_PASSWORD, true)
        .await
        .expect("the self-service change succeeds")
        .expect("a self-service change issues a pair");
    assert_eq!(unrevoked_refresh_tokens(&app.pool, ada.id).await, 1);
    assert_eq!(issued.user.auth_version, 1);
    credentials
        .refresh(&presented(&issued.refresh_cookie))
        .await
        .expect("the replacement is usable");

    // A wrong current password is the message the frontend matches verbatim.
    let err = credentials
        .change_password(ada.id, Some(PASSWORD.to_string()), PASSWORD, true)
        .await
        .expect_err("the stale current password is refused");
    assert_eq!(err.status(), StatusCode::BAD_REQUEST);
    assert_eq!(err.user_message(), "current password is incorrect");

    // An administrator's change: no pair, and nothing left unrevoked.
    assert!(
        credentials
            .change_password(ada.id, None, PASSWORD, false)
            .await
            .expect("the administrator's change succeeds")
            .is_none()
    );
    assert_eq!(unrevoked_refresh_tokens(&app.pool, ada.id).await, 0);
}

/// Logging out revokes only the presented token and hands back the cookie that
/// clears it; a jar with no cookie is still a 204's worth of nothing.
#[tokio::test]
async fn logout_revokes_only_the_presented_token() {
    let app = TestApp::spawn().await;
    let ada = user(&app).await;
    let credentials = Credentials::new(&app.state);

    let one = credentials
        .login(USERNAME, PASSWORD, client())
        .await
        .expect("the first login succeeds");
    credentials
        .login(USERNAME, PASSWORD, client())
        .await
        .expect("the second login succeeds");

    let cleared = credentials
        .logout(&presented(&one.refresh_cookie))
        .await
        .expect("the logout succeeds");

    assert_eq!(cleared.name(), REFRESH_COOKIE);
    assert_eq!(cleared.value(), "");
    assert_eq!(cleared.max_age().expect("a max-age").whole_seconds(), 0);

    // The other browser is untouched.
    assert_eq!(unrevoked_refresh_tokens(&app.pool, ada.id).await, 1);

    // No cookie at all is not a failure.
    credentials
        .logout(&CookieJar::new())
        .await
        .expect("logging out without a cookie succeeds");
}
