//! The `rmcp` handler the Streamable HTTP service builds one of per MCP
//! session (`ARCHITECTURE.md`, "MCP design").
//!
//! It holds nothing session-specific: the factory in [`super::mcp_router`]
//! clones [`AppState`] and nothing else, and everything about the *calling*
//! session comes from the per-request [`SessionContext`]. That split is what
//! lets the bearer middleware run per HTTP request while the MCP session,
//! which is keyed by `Mcp-Session-Id` and outlives a token rotation, stays
//! ignorant of tokens.
//!
//! [`ServerHandler::list_tools`] and [`ServerHandler::call_tool`] are written
//! out by hand rather than generated by `rmcp`'s `#[tool_router]`/`#[tool]`
//! macros: those build one static tool list per server type, and the listing
//! here depends on the *calling* session's profile (`ARCHITECTURE.md`, "MCP
//! design" → Tool exposure).

use rmcp::ServerHandler;
use rmcp::model::{
    CacheScope, CallToolRequestParams, CallToolResponse, CallToolResult, ContentBlock, ErrorData,
    Implementation, ListToolsResult, PaginatedRequestParams, ServerCapabilities, ServerConfig,
};
use rmcp::service::{RequestContext, RoleServer};
use serde_json::{Map, Value};

use crate::prelude::*;

use super::tools::{self, ToolName};
use super::{McpError, SessionContext};

/// How the server names itself in `initialize` (`ARCHITECTURE.md`, "MCP
/// design", Per-session config file: the same name the generated `mcp.json`
/// gives the server, chosen over the bare `mars` so a repository's own
/// `.mcp.json` is unlikely to shadow it).
const SERVER_NAME: &str = "mars-orchestrator";

/// The one-paragraph brief the CLI puts in front of the model. Short and
/// opinionated on purpose (`ARCHITECTURE.md`, "MCP design", Tool exposure).
const INSTRUCTIONS: &str = "Mars task tracker and git tools. Call ready to find work, claim before working, comment before handing off.";

/// How long a client may treat one `tools/list` answer as fresh.
///
/// The listing depends on the calling session's profile and nothing else, and
/// a profile edit is the only thing that changes it, so a minute is short
/// enough for an edit to show up and long enough that a client does not list
/// again before every call.
const TOOL_LIST_TTL_MS: u64 = 60_000;

/// What the server advertises in its `initialize` response.
///
/// A free function rather than a method because it reads nothing from the
/// state: the identity, the one capability and the instructions are constants,
/// and keeping them out of `self` is what lets a unit test assert on them
/// without building an [`AppState`].
fn server_info() -> ServerConfig {
    ServerConfig::new(ServerCapabilities::builder().enable_tools().build())
        .with_server_info(Implementation::new(SERVER_NAME, env!("CARGO_PKG_VERSION")))
        .with_instructions(INSTRUCTIONS)
}

/// The MCP handler. One per MCP session, built by the factory closure in
/// [`super::mcp_router`].
#[derive(Clone)]
pub struct McpServer {
    state: AppState,
}

impl McpServer {
    pub fn new(state: AppState) -> Self {
        Self { state }
    }

    /// The calling session, as the bearer middleware resolved it.
    ///
    /// **How the pinned `rmcp` forwards HTTP request data.** Verified against
    /// `rmcp` 3.4.0: `StreamableHttpService` consumes the request body and
    /// inserts the remaining `http::request::Parts` — extensions included —
    /// into the `RequestContext`'s own extensions, and nothing else of the
    /// HTTP request travels with the MCP message (see that type's "Accessing
    /// HTTP request data from tool handlers", and the
    /// `extensions_mut().insert(part)` calls on every dispatch path in
    /// `transport::streamable_http_server::tower`). So an `axum` middleware
    /// that inserts a [`SessionContext`] into the *request* extensions is read
    /// back here through `Parts`, and not directly off `ctx.extensions`.
    ///
    /// The direct lookup is tried first all the same: it costs one map probe,
    /// it is what a future `rmcp` that flattens the extensions would populate,
    /// and it is how a test can supply a context without an HTTP request at
    /// all.
    ///
    /// A missing context means the middleware did not run — a wiring fault,
    /// not a caller's mistake — so it is logged and answered as an internal
    /// error rather than panicking the session's whole connection.
    // Not the crate's `Result` alias: an MCP handler answers with `ErrorData`,
    // which the JSON-RPC envelope carries, rather than with the HTTP `Error`.
    fn context(
        &self,
        ctx: &RequestContext<RoleServer>,
    ) -> std::result::Result<SessionContext, ErrorData> {
        let resolved = ctx
            .extensions
            .get::<SessionContext>()
            .or_else(|| {
                ctx.extensions
                    .get::<axum::http::request::Parts>()
                    .and_then(|parts| parts.extensions.get::<SessionContext>())
            })
            .cloned();

        match resolved {
            Some(context) => {
                debug!(session_id = %context.session_id, "mcp request context resolved");
                Ok(context)
            }
            None => {
                error!("mcp request without session context");
                Err(ErrorData::internal_error("internal error", None))
            }
        }
    }

    /// One authenticated `tools/call`, from the name on the wire to the
    /// handler's JSON.
    ///
    /// The order is the documented one: an unknown name is the caller's
    /// mistake (`invalid_argument`), a known one outside the profile is a
    /// refusal (`forbidden`), and only then are the arguments parsed and the
    /// handler run.
    async fn invoke(
        &self,
        context: &SessionContext,
        name: &str,
        arguments: Option<Map<String, Value>>,
    ) -> super::McpResult<Value> {
        let Some(tool) = ToolName::parse(name) else {
            return Err(McpError::invalid_argument(format!("unknown tool: {name}")));
        };

        if !is_allowed(tool, &context.profile.mcp_tools) {
            // A profile fault rather than a protocol one: the tool was never
            // listed to this session, so an agent calling it has either cached
            // a stale listing or invented the call.
            warn!(
                session_id = %context.session_id,
                tool = name,
                "mcp tool is not allowed for this profile",
            );
            return Err(McpError::forbidden(format!(
                "tool {name} is not allowed for this profile"
            )));
        }

        // Absent arguments are an empty object: a tool whose fields are all
        // optional — `ready`, `list_session_branches` — is callable with no
        // `arguments` key at all. A body that is not an object never reaches
        // here: `rmcp` types `arguments` as a JSON object and refuses an array
        // or a scalar in the JSON-RPC envelope, before any handler is chosen.
        let args = Value::Object(arguments.unwrap_or_default());

        tools::dispatch(&self.state, context, tool, args).await
    }
}

/// Is this tool listed and callable for a profile with these `mcp_tools`?
///
/// The eight task tools always are; the four git tools only when named, exactly
/// and case-sensitively (`SPEC.md`, "MCP tool contracts"; `docs/data-model.md`,
/// `agent_profiles.mcp_tools`). A task tool named in `mcp_tools` therefore
/// changes nothing, and a name that matches no tool at all is ignored here —
/// rejecting those is profile validation's job.
fn is_allowed(tool: ToolName, mcp_tools: &[String]) -> bool {
    !tool.is_git() || mcp_tools.iter().any(|name| name == tool.as_str())
}

/// The tool's JSON as both a structured result and a text block.
///
/// `structured_content` is the answer the contract defines; the text block is
/// the same JSON verbatim, so a client that predates structured content still
/// shows the model something useful rather than an empty result.
fn tool_result(value: Value) -> CallToolResult {
    // `Display` for `Value` is compact JSON and cannot fail, unlike
    // `serde_json::to_string`, which would need an `unwrap` here.
    let text = value.to_string();
    let mut result = CallToolResult::success(vec![ContentBlock::text(text)]);
    result.structured_content = Some(value);

    result
}

impl ServerHandler for McpServer {
    fn get_info(&self) -> ServerConfig {
        server_info()
    }

    /// The tools this session may call: the eight task tools always, and each
    /// git tool only when the profile names it.
    ///
    /// The profile comes from the per-request [`SessionContext`], so an edit to
    /// `mcp_tools` takes effect on the session's next request without a
    /// relaunch. A CLI that cached an older listing is not a problem: the gate
    /// that matters is in [`McpServer::invoke`], and a call to a newly allowed
    /// tool succeeds whether or not the client has seen it listed.
    ///
    /// One page: twelve tools need no cursor, so `next_cursor` stays absent.
    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        ctx: RequestContext<RoleServer>,
    ) -> std::result::Result<ListToolsResult, ErrorData> {
        let context = self.context(&ctx)?;

        let tools = tools::catalog()
            .iter()
            .filter(|tool| match ToolName::parse(&tool.name) {
                Some(name) => is_allowed(name, &context.profile.mcp_tools),
                // Unreachable: the catalog is built from `ToolName::ALL`.
                None => false,
            })
            .cloned()
            .collect();

        // Protocol revision 2026-07-28 makes `ttlMs` and `cacheScope` required
        // on a list result, and `rmcp` 3.4.0 leaves both unset unless told.
        // The pinned Claude Code CLI negotiates that revision and validates
        // the result against it: without the two fields it discards the whole
        // listing and the session has no Mars tools at all. `private`, because
        // the listing is this session's — filtered by its profile — and no
        // other caller's (`ARCHITECTURE.md`, "MCP design").
        Ok(ListToolsResult::with_all_items(tools)
            .with_ttl_ms(TOOL_LIST_TTL_MS)
            .with_cache_scope(CacheScope::Private))
    }

    /// One tool call.
    ///
    /// **Panics.** A handler is not wrapped in a `spawn` of its own: verified
    /// against `rmcp` 3.4.0, the serve loop already spawns one task per
    /// incoming request (`service.rs`, the `Event::PeerMessage` request arm),
    /// so a panicking handler unwinds that task alone and leaves the listener,
    /// the MCP session and every concurrent call untouched. The panicking call
    /// itself simply never answers, which is what a `JoinHandle` mapped to
    /// `internal` would improve on — at the price of a second task per call
    /// for a case that is a bug either way.
    ///
    /// **Concurrency.** `rmcp` may deliver calls of one MCP session at the same
    /// time. Nothing here is per-call state: the handler holds only
    /// [`AppState`], the catalog is immutable and the context is per request.
    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        ctx: RequestContext<RoleServer>,
    ) -> std::result::Result<CallToolResponse, ErrorData> {
        let context = self.context(&ctx)?;
        let name = request.name;

        // One line per call, at `debug`, naming what was called and how it
        // ended. Arguments and results are never logged at all: they carry task
        // descriptions, comments and commit messages (`CLAUDE.md`, "Logging").
        match self.invoke(&context, &name, request.arguments).await {
            Ok(value) => {
                debug!(
                    session_id = %context.session_id,
                    project_id = %context.project_id,
                    tool = %name,
                    ok = true,
                    "mcp tool call",
                );
                Ok(tool_result(value).into())
            }
            Err(err) => {
                debug!(
                    session_id = %context.session_id,
                    project_id = %context.project_id,
                    tool = %name,
                    ok = false,
                    code = err.code.as_str(),
                    "mcp tool call",
                );
                Err(err.into())
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_server_names_itself_as_the_generated_mcp_json_does() {
        assert_eq!(server_info().server_info.name, "mars-orchestrator");
    }

    #[test]
    fn the_instructions_are_the_documented_brief() {
        assert_eq!(
            server_info().instructions.as_deref(),
            Some(
                "Mars task tracker and git tools. Call ready to find work, claim before working, comment before handing off."
            )
        );
    }

    #[test]
    fn a_profile_that_names_no_tool_still_gets_every_task_tool() {
        let allowed: Vec<_> = ToolName::ALL
            .into_iter()
            .filter(|tool| is_allowed(*tool, &[]))
            .map(ToolName::as_str)
            .collect();

        assert_eq!(
            allowed,
            [
                "ready",
                "claim",
                "get_task",
                "update",
                "release",
                "comment",
                "needs_human",
                "create_task",
            ],
        );
    }

    #[test]
    fn a_git_tool_is_allowed_only_when_the_profile_names_it_exactly() {
        let merge_only = ["merge".to_string()];

        assert!(is_allowed(ToolName::Merge, &merge_only));
        assert!(!is_allowed(ToolName::Rebase, &merge_only));
        assert!(!is_allowed(ToolName::Push, &merge_only));

        // Exact and case-sensitive.
        for spelling in ["Merge", "MERGE", " merge", "merge "] {
            assert!(
                !is_allowed(ToolName::Merge, &[spelling.to_string()]),
                "{spelling}",
            );
        }
    }

    #[test]
    fn naming_a_task_tool_or_a_tool_that_does_not_exist_changes_nothing() {
        let noise = [
            "ready".to_string(),
            "create_task".to_string(),
            "sudo".to_string(),
        ];

        assert!(is_allowed(ToolName::Ready, &noise));
        assert!(!is_allowed(ToolName::Merge, &noise));
    }

    #[test]
    fn a_result_carries_the_same_json_structured_and_as_text() {
        let value = serde_json::json!({ "task": { "number": 12 } });
        let result = tool_result(value.clone());

        assert_eq!(result.structured_content, Some(value));
        assert_eq!(result.is_error, Some(false));
        assert_eq!(
            serde_json::to_value(&result.content).unwrap(),
            serde_json::json!([{ "type": "text", "text": r#"{"task":{"number":12}}"# }]),
        );
    }

    #[test]
    fn tools_are_the_only_capability_advertised() {
        let capabilities = server_info().capabilities;

        assert!(capabilities.tools.is_some(), "tools are advertised");
        assert!(capabilities.prompts.is_none());
        assert!(capabilities.resources.is_none());
        assert!(capabilities.logging.is_none());
        assert!(capabilities.completions.is_none());
        assert!(capabilities.experimental.is_none());
        assert!(capabilities.extensions.is_none());
    }
}
